module.exports = {
  caseA: {
    cause_history: [
      {book: '1 Principal', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
      {book: '2 Apremio Ejecutivo Obligación de Dar', history: [
        {
          folio: '48',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '3',
        },
      ]},
    ],
    exhorts: [
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-808-2018',
        exhort_order_date: '05/04/2018',
        exhort_added_date: '05/04/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-307-2019',
        exhort_order_date: '02/02/2019',
        exhort_added_date: '02/02/2019',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Generado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2562-2018',
        exhort_order_date: '10/10/2018',
        exhort_added_date: '10/10/2018',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2054-2018',
        exhort_order_date: '13/08/2018',
        exhort_added_date: '13/08/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
    ],
    pending_docs: [
      {book: '1 Principal', docs: []},
      {book: '2 Apremio Ejecutivo Obligación de Dar', docs: []},
    ],
    receptor: [{book: 'Causa no presenta retiro de Receptor.'}],
    role_search: [
      {
        role: 'C-546-2018 ',
        date: '08/01/2018',
        cover: 'TANNER SERVICIOS FINANCIEROS S.A./MADARIAGA',
        court: '27º Juzgado Civil de Santiago',
      },
    ],
    status: 'Archivada',
    case_id: '123',
  },
  caseB: {
    cause_history: [
      {book: '1 Principal', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
        {
          folio: '45',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveídow',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
      {book: '2 Apremio Ejecutivo Obligación de Dar', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
    ],
    exhorts: [
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-808-2018',
        exhort_order_date: '05/04/2018',
        exhort_added_date: '05/04/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-307-2019',
        exhort_order_date: '02/02/2019',
        exhort_added_date: '02/02/2019',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Generado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2562-2018',
        exhort_order_date: '10/10/2018',
        exhort_added_date: '10/10/2018',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2054-2018',
        exhort_order_date: '13/08/2018',
        exhort_added_date: '13/08/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
    ],
    pending_docs: [
      {book: '1 Principal', docs: []},
      {book: '2 Apremio Ejecutivo Obligación de Dar', docs: []},
    ],
    receptor: [{book: 'Causa no presenta retiro de Receptor.'}],
    role_search: [
      {
        role: 'C-546-2018 ',
        date: '08/01/2018',
        cover: 'TANNER SERVICIOS FINANCIEROS S.A./MADARIAGA',
        court: '27º Juzgado Civil de Santiago',
      },
    ],
    status: 'Archivada',
    case_id: '123',
  },
  caseC: {
    cause_history: [
      {book: '1 Principal', history: [
      ]},
      {book: '2 Apremio Ejecutivo Obligación de Dar', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
    ],
    exhorts: [
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-808-2018',
        exhort_order_date: '05/04/2018',
        exhort_added_date: '05/04/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-307-2019',
        exhort_order_date: '02/02/2019',
        exhort_added_date: '02/02/2019',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Generado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2562-2018',
        exhort_order_date: '10/10/2018',
        exhort_added_date: '10/10/2018',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2054-2018',
        exhort_order_date: '13/08/2018',
        exhort_added_date: '13/08/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
    ],
    pending_docs: [
      {book: '1 Principal', docs: []},
      {book: '2 Apremio Ejecutivo Obligación de Dar', docs: []},
    ],
    receptor: [{book: 'Causa no presenta retiro de Receptor.'}],
    role_search: [
      {
        role: 'C-546-2018 ',
        date: '08/01/2018',
        cover: 'TANNER SERVICIOS FINANCIEROS S.A./MADARIAGA',
        court: '27º Juzgado Civil de Santiago',
      },
    ],
    status: 'Archivada',
    case_id: '123',
  },
  caseD: {
    cause_history: [
      {book: '1 Principal', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
      {book: '2 Apremio Ejecutivo Obligación de Dar', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
    ],
    exhorts: [
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-808-2018',
        exhort_order_date: '05/04/2018',
        exhort_added_date: '05/04/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-307-2019',
        exhort_order_date: '02/02/2019',
        exhort_added_date: '02/02/2019',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Generado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2562-2018',
        exhort_order_date: '10/10/2018',
        exhort_added_date: '10/10/2018',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2054-2018',
        exhort_order_date: '13/08/2018',
        exhort_added_date: '13/08/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2054-2018',
        exhort_order_date: '13/08/2018',
        exhort_added_date: '13/08/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
    ],
    pending_docs: [
      {book: '1 Principal', docs: []},
      {book: '2 Apremio Ejecutivo Obligación de Dar', docs: []},
    ],
    receptor: [{book: 'Causa no presenta retiro de Receptor.'}],
    role_search: [
      {
        role: 'C-546-2018 ',
        date: '08/01/2018',
        cover: 'TANNER SERVICIOS FINANCIEROS S.A./MADARIAGA',
        court: '27º Juzgado Civil de Santiago',
      },
    ],
    status: 'Archivada',
    case_id: '123',
  },
  caseE: {
    cause_history: [
      {book: '1 Principal', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
      {book: '2 Apremio Ejecutivo Obligación de Dar', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
    ],
    exhorts: [
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-808-2018',
        exhort_order_date: '05/04/2018',
        exhort_added_date: '05/04/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-307-2019',
        exhort_order_date: '02/02/2019',
        exhort_added_date: '02/02/2019',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Generado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
    ],
    pending_docs: [
      {book: '1 Principal', docs: []},
      {book: '2 Apremio Ejecutivo Obligación de Dar', docs: []},
    ],
    receptor: [{book: 'Causa no presenta retiro de Receptor.'}],
    role_search: [
      {
        role: 'C-546-2018 ',
        date: '08/01/2018',
        cover: 'TANNER SERVICIOS FINANCIEROS S.A./MADARIAGA',
        court: '27º Juzgado Civil de Santiago',
      },
    ],
    status: 'Archivada',
    case_id: '123',
  },
  caseF: {
    cause_history: [
      {book: '1 Principal', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
      {book: '2 Apremio Ejecutivo Obligación de Dar', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
    ],
    exhorts: [
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-808-2018',
        exhort_order_date: '05/04/2018',
        exhort_added_date: '05/04/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-307-2019',
        exhort_order_date: '02/02/2019',
        exhort_added_date: '02/02/2019',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Generado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2562-2018',
        exhort_order_date: '10/10/2018',
        exhort_added_date: '10/10/2018',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2054-2018',
        exhort_order_date: '13/08/2018',
        exhort_added_date: '13/08/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
    ],
    pending_docs: [
      {book: '1 Principal', docs: ['one doc']},
      {book: '2 Apremio Ejecutivo Obligación de Dar', docs: []},
    ],
    receptor: [{book: 'Causa no presenta retiro de Receptor.'}],
    role_search: [
      {
        role: 'C-546-2018 ',
        date: '08/01/2018',
        cover: 'TANNER SERVICIOS FINANCIEROS S.A./MADARIAGA',
        court: '27º Juzgado Civil de Santiago',
      },
    ],
    status: 'Archivada',
    case_id: '123',
  },
  caseG: {
    cause_history: [
      {book: '1 Principal', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
      {book: '2 Apremio Ejecutivo Obligación de Dar', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
    ],
    exhorts: [
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-808-2018',
        exhort_order_date: '05/04/2018',
        exhort_added_date: '05/04/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-307-2019',
        exhort_order_date: '02/02/2019',
        exhort_added_date: '02/02/2019',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Generado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2562-2018',
        exhort_order_date: '10/10/2018',
        exhort_added_date: '10/10/2018',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2054-2018',
        exhort_order_date: '13/08/2018',
        exhort_added_date: '13/08/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
    ],
    pending_docs: [
      {book: '1 Principal', docs: []},
      {book: '2 Apremio Ejecutivo Obligación de Dar', docs: []},
    ],
    receptor: [{book: 'Carlos Peralta receptor'}],
    role_search: [
      {
        role: 'C-546-2018 ',
        date: '08/01/2018',
        cover: 'TANNER SERVICIOS FINANCIEROS S.A./MADARIAGA',
        court: '27º Juzgado Civil de Santiago',
      },
    ],
    status: 'Archivada',
    case_id: '123',
  },
  caseH: {
    cause_history: [
      {book: '1 Principal', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
      {book: '2 Apremio Ejecutivo Obligación de Dar', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
    ],
    exhorts: [
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-808-2018',
        exhort_order_date: '05/04/2018',
        exhort_added_date: '05/04/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-307-2019',
        exhort_order_date: '02/02/2019',
        exhort_added_date: '02/02/2019',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Generado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2562-2018',
        exhort_order_date: '10/10/2018',
        exhort_added_date: '10/10/2018',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2054-2018',
        exhort_order_date: '13/08/2018',
        exhort_added_date: '13/08/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2054-2018',
        exhort_order_date: '13/08/2018',
        exhort_added_date: '13/08/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
    ],
    pending_docs: [
      {book: '1 Principal', docs: ['this is a test']},
      {book: '2 Apremio Ejecutivo Obligación de Dar', docs: []},
    ],
    receptor: [{book: 'Carlos Peralta receptor'}],
    role_search: [
      {
        role: 'C-546-2018 ',
        date: '08/01/2018',
        cover: 'TANNER SERVICIOS FINANCIEROS S.A./MADARIAGA',
        court: '27º Juzgado Civil de Santiago',
      },
    ],
    status: 'Archivada',
    case_id: '123',
  },
  caseI: {
    cause_history: [
      {book: '1 Principal', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
      {book: '2 Apremio Ejecutivo Obligación de Dar', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
    ],
    exhorts: [
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-808-2018',
        exhort_order_date: '05/04/2018',
        exhort_added_date: '05/04/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-307-2019',
        exhort_order_date: '02/02/2019',
        exhort_added_date: '02/02/2019',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Generado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2562-2018',
        exhort_order_date: '10/10/2018',
        exhort_added_date: '10/10/2018',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2054-2018',
        exhort_order_date: '13/08/2018',
        exhort_added_date: '13/08/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
    ],
    pending_docs: [
      {book: '1 Principal', docs: []},
      {book: '2 Apremio Ejecutivo Obligación de Dar', docs: []},
    ],
    receptor: [{book: 'Causa no presenta retiro de Receptor.'}],
    role_search: [
      {
        role: 'C-546-2018 ',
        date: '08/01/2018',
        cover: 'TANNER SERVICIOS FINANCIEROS S.A./MADARIAGA',
        court: '27º Juzgado Civil de Santiago',
      },
    ],
    status: 'Archivada',
    case_id: '123',
  },
  caseJ: {
    cause_history: [
      {book: '1 Principal', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
      {book: '2 Apremio Ejecutivo Obligación de Dar', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
    ],
    exhorts: [
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-808-2018',
        exhort_order_date: '05/04/2018',
        exhort_added_date: '05/04/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-307-2019',
        exhort_order_date: '02/02/2019',
        exhort_added_date: '02/02/2019',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Generado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2562-2018',
        exhort_order_date: '10/10/2018',
        exhort_added_date: '10/10/2018',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2054-2018',
        exhort_order_date: '13/08/2018',
        exhort_added_date: '13/08/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2054-2018',
        exhort_order_date: '13/08/2018',
        exhort_added_date: '13/08/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
    ],
    pending_docs: [
      {book: '1 Principal', docs: ['this is a test']},
      {book: '2 Apremio Ejecutivo Obligación de Dar', docs: []},
    ],
    receptor: [{book: 'Carlos Peralta receptor'}],
    role_search: [
      {
        role: 'C-546-2018 ',
        date: '08/01/2018',
        cover: 'TANNER SERVICIOS FINANCIEROS S.A./MADARIAGA',
        court: '27º Juzgado Civil de Santiago',
      },
    ],
    status: 'Archivada',
    case_id: '123',
  },
}
