module.exports = {
  courts: [
    {'name': '5º Juzgado Civil de Santiago', 'external_id': '263'},
    {'name': '20º Juzgado Civil de Santiago', 'external_id': '278'},
    {'name': '9º Juzgado Civil de Santiago', 'external_id': '267'},
    {'name': '22º Juzgado Civil de Santiago', 'external_id': '280'},
    {'name': '15º Juzgado Civil de Santiago', 'external_id': '273'},
    {'name': '4º Juzgado Civil de Santiago', 'external_id': '262'},
    {'name': '1º Juzgado Civil de Santiago', 'external_id': '259'},
    {'name': '13º Juzgado Civil de Santiago', 'external_id': '271'},
    {'name': '18º Juzgado Civil de Santiago', 'external_id': '276'},
    {'name': '21º Juzgado Civil de Santiago', 'external_id': '279'},
    {'name': '19º Juzgado Civil de Santiago', 'external_id': '277'},
    {'name': '24º Juzgado Civil de Santiago', 'external_id': '282'},
    {'name': '12º Juzgado Civil de Santiago', 'external_id': '270'},
    {'name': '14º Juzgado Civil de Santiago', 'external_id': '272'},
    {'name': '17º Juzgado Civil de Santiago', 'external_id': '275'},
    {'name': '28º Juzgado Civil de Santiago', 'external_id': '286'},
    {'name': '2º Juzgado Civil de Santiago', 'external_id': '260'},
    {'name': '3º Juzgado Civil de Santiago', 'external_id': '261'},
    {'name': '6º Juzgado Civil de Santiago', 'external_id': '264'},
    {'name': '8º Juzgado Civil de Santiago', 'external_id': '266'},
    {'name': '23º Juzgado Civil de Santiago', 'external_id': '281'},
    {'name': '10º Juzgado Civil de Santiago', 'external_id': '268'},
    {'name': '11º Juzgado Civil de Santiago', 'external_id': '269'},
    {'name': '16º Juzgado Civil de Santiago', 'external_id': '274'},
    {'name': '7º Juzgado Civil de Santiago', 'external_id': '265'},
    {'name': '29º Juzgado Civil de Santiago', 'external_id': '287'},
    {'name': '30º Juzgado Civil de Santiago', 'external_id': '288'},
    {'name': '26º Juzgado Civil de Santiago', 'external_id': '284'},
    {'name': '25º Juzgado Civil de Santiago', 'external_id': '283'},
    {'name': '27º Juzgado Civil de Santiago', 'external_id': '285'},
    {'name': 'Juzgado de Letras de Colina', 'external_id': '387'},
    {'name': '3º Juzgado de Letras de Iquique', 'external_id': '11'},
    {'name': '1º Juzgado Civil de San Miguel', 'external_id': '343'},
    {'name': 'Juzgado de Letras de Peñaflor', 'external_id': '388'},
    {'name': '3º Juzgado de Letras de Calama', 'external_id': '658'},
    {'name': '3º Juzgado de Letras Civil de Antofagasta',
      'external_id': '1043'},
  ],
  clients: {
    zonaSur: {
      'name': 'ZonaSur',
      'external_id': '0',
      'is_active': true,
    },
  },
  user: {
    email: 'carlos@test.com',
    client: {external_id: '0'},
    external_id: 'chichi',
    is_active: true,
  },
  case: [{'external_id': '40692',
    'role': 'C-3163-2018',
    'court_id': 285,
    'clients': ['0'],
    'emails': ['carlos@test.com']}],
  caseDataA: {body: {
    cause_history: [
      {book: '1 Principal', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
      {book: '2 Apremio Ejecutivo Obligación de Dar', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
    ],
    exhorts: [
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-808-2018',
        exhort_order_date: '05/04/2018',
        exhort_added_date: '05/04/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-307-2019',
        exhort_order_date: '02/02/2019',
        exhort_added_date: '02/02/2019',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Generado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2562-2018',
        exhort_order_date: '10/10/2018',
        exhort_added_date: '10/10/2018',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2054-2018',
        exhort_order_date: '13/08/2018',
        exhort_added_date: '13/08/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
    ],
    pending_docs: [
      {book: '1 Principal', docs: []},
      {book: '2 Apremio Ejecutivo Obligación de Dar', docs: []},
    ],
    receptor: [{book: 'Causa no presenta retiro de Receptor.'}],
    role_search: [
      {
        role: 'C-3163-2018 ',
        date: '08/01/2018',
        cover: 'TANNER SERVICIOS FINANCIEROS S.A./MADARIAGA',
        court: '27º Juzgado Civil de Santiago',
      },
    ],
    status: 'Archivada',
  },
  params: {
    role: 'C-3163-2018',
  }},
  caseDataB: {body: {
    cause_history: [
      {book: '1 Principal', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
      {book: '2 Apremio Ejecutivo Obligación de Dar', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
    ],
    exhorts: [
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-307-2019',
        exhort_order_date: '02/02/2019',
        exhort_added_date: '02/02/2019',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Generado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2562-2018',
        exhort_order_date: '10/10/2018',
        exhort_added_date: '10/10/2018',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2054-2018',
        exhort_order_date: '13/08/2018',
        exhort_added_date: '13/08/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
    ],
    pending_docs: [
      {book: '1 Principal', docs: []},
      {book: '2 Apremio Ejecutivo Obligación de Dar', docs: []},
    ],
    receptor: [{book: 'Causa no presenta retiro de Receptor.'}],
    role_search: [
      {
        role: 'C-3163-2018 ',
        date: '08/01/2018',
        cover: 'TANNER SERVICIOS FINANCIEROS S.A./MADARIAGA',
        court: '27º Juzgado Civil de Santiago',
      },
    ],
    status: 'Archivada',
  },
  params: {
    role: 'C-3163-2018',
  }},
  caseDataC: {body: {
    cause_history: [
      {book: '1 Principal', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
      {book: '2 Apremio Ejecutivo Obligación de Dar', history: [
        {
          folio: '47',
          doc: '',
          attachment: '',
          stage: 'Notificación demanda y su proveído',
          procedure: 'Resolución',
          procedure_description: 'Archivo del expediente en el Tribunal',
          procedure_date: '05/08/2019',
          document_page: '2',
        },
      ]},
    ],
    exhorts: [
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-307-2019',
        exhort_order_date: '02/02/2019',
        exhort_added_date: '02/02/2019',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Generado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2562-2018',
        exhort_order_date: '10/10/2018',
        exhort_added_date: '10/10/2018',
        court_destined: '2º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2054-2018',
        exhort_order_date: '13/08/2018',
        exhort_added_date: '13/08/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
      {
        role_origin: 'C-546-2018',
        exhort_type: 'Exhorto',
        role_destination: 'E-2054-2018',
        exhort_order_date: '13/08/2018',
        exhort_added_date: '13/08/2018',
        court_destined: '1º Juzgado Civil de Rancagua',
        exhort_status: 'Recepcionado',
        role_destination_detail: [
          {doc: '',
            date: '15/05/2018',
            reference: 'Folio:5 Diligenciado con resultado negativo',
            procedure: 'Resolución',
          },
        ],
      },
    ],
    pending_docs: [
      {book: '1 Principal', docs: []},
      {book: '2 Apremio Ejecutivo Obligación de Dar', docs: []},
    ],
    receptor: [{book: 'Causa no presenta retiro de Receptor.'}],
    role_search: [
      {
        role: 'C-3163-2018 ',
        date: '08/01/2018',
        cover: 'TANNER SERVICIOS FINANCIEROS S.A./MADARIAGA',
        court: '27º Juzgado Civil de Santiago',
      },
    ],
    status: 'Archivada',
  },
  params: {
    role: 'C-3163-2018',
  }}}
